namespace OrdersPerformanceTestApi.Models
{
    using Swashbuckle.AspNetCore.Annotations;
    using System.ComponentModel.DataAnnotations;

    public class OrderProduct
    {
        [SwaggerSchema(ReadOnly = true, Description = "Auto-generated by the database.")]
        [Key]
        public int Id { get; set; }

        [Required]
        public int OrderId { get; set; }

        [Required]
        public int ProductId { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1.")]
        public int Quantity { get; set; }

        [Range(0.01, double.MaxValue, ErrorMessage = "Price must be greater than 0.")]
        public decimal Price { get; set; }

        // Navigation property to the Order entity.
        public Order Order { get; set; }

        // Navigation property to the Product entity.
        public Product Product { get; set; }
    }
}