namespace OrdersPerformanceTestApi.Models
{
    using Swashbuckle.AspNetCore.Annotations;
    using System.ComponentModel.DataAnnotations;

    public class Order
    {
        [SwaggerSchema(ReadOnly = true, Description = "Auto-generated by the database.")]
        [Key]
        public int Id { get; set; }

        [Required]
        public int UserId { get; set; }

        [Required]
        public DateTime DateAdded { get; set; }

        // Navigation property to the User entity.
        public User User { get; set; }

        // Navigation property to the OrderProducts entity.
        public ICollection<OrderProduct> OrderProducts { get; set; }
    }
}