namespace OrdersPerformanceTestApi.Models
{
    using Swashbuckle.AspNetCore.Annotations;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    public class Product
    {
        [SwaggerSchema(ReadOnly = true, Description = "Auto-generated by the database.")]
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Product name is required.")]
        [StringLength(100, ErrorMessage = "Product name cannot exceed 100 characters.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Price is required.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Price must be greater than 0.")]
        public decimal Price { get; set; }

        [JsonIgnore]
        public virtual ICollection<OrderProduct>? OrderProducts { get; set; }
    }
}