namespace OrdersPerformanceTestApi.Models
{
    using Swashbuckle.AspNetCore.Annotations;
    using System.ComponentModel.DataAnnotations;

    public class User
    {
        [SwaggerSchema(ReadOnly = true, Description = "Auto-generated by the database.")]
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        [StringLength(100, ErrorMessage = "Name cannot exceed 100 characters.")]
        public string Name { get; set; }

        // Navigation property to the Orders entity.
        public ICollection<Order> Orders { get; set; }
    }
}